/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-shopee-products.ts — ห้ามแก้ด้วยมือ
// รันใหม่ด้วย: npm run shopee:fetch  (ปรับหมวด/คำค้นที่ scripts/shopee-buckets.ts)
// อัปเดตล่าสุด: 2026-07-23 — 18 สินค้า
import type { ShopeeProduct } from "./shopee-products";

export const GENERATED_PRODUCTS: ShopeeProduct[] = [
  {
    "id": "shopee-28092608076",
    "title": "EYESPRO สว่างทั้งคืน โคมไฟตั้งโต๊ะ LED โคมไฟแม่เหล็ก ฟข้างเตียง แสงไฟ ถนอมสายตา ไฟติดห้อง โคมไฟไร้สาย ปรับได้ 3 แสง",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1198178537%2F28092608076",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81ztd-mm1hcpmw0cn88a",
    "price": 104,
    "note": "จัดโต๊ะให้ทำงานกับ AI ได้นานขึ้น ไม่ปวดคอปวดหลัง",
    "category": "อุปกรณ์ทำงาน",
    "tags": [
      "ทำงาน",
      "ประสิทธิภาพ",
      "prompt"
    ],
    "featured": true
  },
  {
    "id": "shopee-53352530007",
    "title": "Moreno ชุดอุปกรณ์เสริมทำความสะอาด 33in1 ใช้กับคีย์บอร์ด หูฟัง โทรศัพท์ กล้อง ทำความสะอาดได้ทุกมุม",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F218401169%2F53352530007",
    "imageUrl": "https://cf.shopee.co.th/file/sg-11134201-8226v-mhsvs77t3zm05b",
    "price": 99,
    "note": "จัดโต๊ะให้ทำงานกับ AI ได้นานขึ้น ไม่ปวดคอปวดหลัง",
    "category": "อุปกรณ์ทำงาน",
    "tags": [
      "ทำงาน",
      "ประสิทธิภาพ",
      "prompt"
    ],
    "featured": true
  },
  {
    "id": "shopee-12457690376",
    "title": "[โค้ดคุ้มลด 20%] Sticker Keyboard สติกเกอร์ คีย์บอร์ด ภาษาไทย Die cut sticker รุ่นไดคัท (ตัดวงกลมให้เเล้ว) sticker thai",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F9371370%2F12457690376",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-7r991-lrod95d076niba",
    "price": 39,
    "note": "จัดโต๊ะให้ทำงานกับ AI ได้นานขึ้น ไม่ปวดคอปวดหลัง",
    "category": "อุปกรณ์ทำงาน",
    "tags": [
      "ทำงาน",
      "ประสิทธิภาพ",
      "prompt"
    ],
    "featured": true
  },
  {
    "id": "shopee-29307317905",
    "title": "คิด เลข เครื่องคิดเลข ที่ใช้แบตเตอรี่ 12 หลัก หน้าจอขนาดใหญ่ เอียง 15 องศา แป้นพิมพ์กล Onesuper",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F567457225%2F29307317905",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-7r990-lyojc2k4hmspfa",
    "price": 109,
    "note": "จัดโต๊ะให้ทำงานกับ AI ได้นานขึ้น ไม่ปวดคอปวดหลัง",
    "category": "อุปกรณ์ทำงาน",
    "tags": [
      "ทำงาน",
      "ประสิทธิภาพ",
      "prompt"
    ],
    "featured": true
  },
  {
    "id": "shopee-27720685213",
    "title": "ทรงแบนสูง-โคมไฟตั้งโต๊ะ LED โคมอ่านหนังสือ แบบไร้สาย ด้วย USB เหมาะสำหรับ ห้องนั่งเล่น ห้องนอน บาร์",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1283699584%2F27720685213",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-7ras8-m6gblc8kws8032",
    "price": 139,
    "note": "จัดโต๊ะให้ทำงานกับ AI ได้นานขึ้น ไม่ปวดคอปวดหลัง",
    "category": "อุปกรณ์ทำงาน",
    "tags": [
      "ทำงาน",
      "ประสิทธิภาพ",
      "prompt"
    ],
    "featured": true
  },
  {
    "id": "shopee-25563300377",
    "title": "MOFii BISCUIT LIPS X910 Wireless Numeric Keypad (คีย์บอร์ดตัวเลขไร้สายสีพาสเทล)",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F45591359%2F25563300377",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-7r991-lro40wlb53sea2",
    "price": 339,
    "note": "จัดโต๊ะให้ทำงานกับ AI ได้นานขึ้น ไม่ปวดคอปวดหลัง",
    "category": "อุปกรณ์ทำงาน",
    "tags": [
      "ทำงาน",
      "ประสิทธิภาพ",
      "prompt"
    ],
    "featured": true
  },
  {
    "id": "shopee-28193919176",
    "title": "4in1 ขาตั้งโน้ตบุ๊ก แท็บเล็ต โทรศัพท์ แล็ปท็อป อลูมิเนียมอัลลอยด์ ขาตั้งมือถือ ปรับได้ ไม้เซลฟี่ ขนาดเล็ก พกพาสะดวก",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F454010068%2F28193919176",
    "imageUrl": "https://cf.shopee.co.th/file/sg-11134201-81zvh-mivhrheqchzadc",
    "price": 228,
    "note": "อุปกรณ์เริ่มทำคอนเทนต์/สอนออนไลน์ หารายได้เสริม",
    "category": "ทำคอนเทนต์",
    "tags": [
      "รายได้",
      "เครื่องมือ"
    ],
    "featured": true
  },
  {
    "id": "shopee-57203220121",
    "title": "Novvia ไมโครโฟนไร้สาย K9 Wireless Microphone K35 แบบพกพา ใช้สําหรับสมาร์ทโฟน ไมค์ไร้สายหนีบเสื้อ ไมค์หนีบปกเสื้อ",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1585528076%2F57203220121",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81zto-micty1fw80eab5",
    "price": 74,
    "note": "อุปกรณ์เริ่มทำคอนเทนต์/สอนออนไลน์ หารายได้เสริม",
    "category": "ทำคอนเทนต์",
    "tags": [
      "รายได้",
      "เครื่องมือ"
    ],
    "featured": true
  },
  {
    "id": "shopee-45657036012",
    "title": "GDT วางโทรศัพท์ ปรับ360องศา phone stand ยืดหดไ ขาตั้งมือถือ ขาจับโทรศัพท์ รับน้ำหนักได้ 5kg ตั้งโต๊ะแข็งแรงมั่นคง",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1744489996%2F45657036012",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81ztd-mln6str1fthcd4",
    "price": 124,
    "note": "อุปกรณ์เริ่มทำคอนเทนต์/สอนออนไลน์ หารายได้เสริม",
    "category": "ทำคอนเทนต์",
    "tags": [
      "รายได้",
      "เครื่องมือ"
    ],
    "featured": true
  },
  {
    "id": "shopee-47551966071",
    "title": "Moreno ขาตั้งมือถือ ขาตั้งโทรศัพท์พร้อมตะขอ พับเก็บได้ มีที่แขวนกระเป๋า น้ำหนักเบา พกพาสะดวก",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F218401169%2F47551966071",
    "imageUrl": "https://cf.shopee.co.th/file/sg-11134201-8225h-mhd7hv5vbfv397",
    "price": 169,
    "note": "อุปกรณ์เริ่มทำคอนเทนต์/สอนออนไลน์ หารายได้เสริม",
    "category": "ทำคอนเทนต์",
    "tags": [
      "รายได้",
      "เครื่องมือ"
    ],
    "featured": true
  },
  {
    "id": "shopee-42261975294",
    "title": "หน้าจอ Auto Clicker สําหรับแอพโทรศัพท์สมาร์ทวิดีโอ Live Streaming Gadget สมาร์ทโฟนหน้าจอเกม Touch ขาตั้งกล้องหน้าจอ Tapper อุปกรณ์",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F290055500%2F42261975294",
    "imageUrl": "https://cf.shopee.co.th/file/cn-11134207-7ras8-md5qetp4v66j4d",
    "price": 261,
    "note": "อุปกรณ์เริ่มทำคอนเทนต์/สอนออนไลน์ หารายได้เสริม",
    "category": "ทำคอนเทนต์",
    "tags": [
      "รายได้",
      "เครื่องมือ"
    ],
    "featured": true
  },
  {
    "id": "shopee-40416115709",
    "title": "Sweet Audio V8 Dynamic Microphone ไมโครโฟน",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F178598541%2F40416115709",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81zth-mm05hndmv401fc",
    "price": 1690,
    "note": "อุปกรณ์เริ่มทำคอนเทนต์/สอนออนไลน์ หารายได้เสริม",
    "category": "ทำคอนเทนต์",
    "tags": [
      "รายได้",
      "เครื่องมือ"
    ],
    "featured": true
  },
  {
    "id": "shopee-27538925624",
    "title": "GOOJODOQ 5000mah Powerbank Ln Type C อินเทอร์เฟซคู่ แบตสํารอง พับได้ พาวเวอร์แบงค์พกพา Power Bank",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1505570169%2F27538925624",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81ztf-mh1da50e0ky179",
    "price": 149,
    "note": "ของช่วยให้ชีวิตทำงาน/เรียนออนไลน์ลื่นขึ้น",
    "category": "แก็ดเจ็ตน่าใช้",
    "tags": [
      "ทำงาน",
      "เครื่องมือ"
    ]
  },
  {
    "id": "shopee-50706240916",
    "title": "Acer OHR721 หูฟังบลูทูธไร้สาย ANC/ENC ระบบตัดเสียงรบกวน TWS Bluetooth 6.0 Touch Control แบต 24ชม. รับประกัน18เดือน",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1589702569%2F50706240916",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81ztl-mkrrqa8azt3abe",
    "price": 459,
    "note": "ของช่วยให้ชีวิตทำงาน/เรียนออนไลน์ลื่นขึ้น",
    "category": "แก็ดเจ็ตน่าใช้",
    "tags": [
      "ทำงาน",
      "เครื่องมือ"
    ]
  },
  {
    "id": "shopee-44473012282",
    "title": "ELRRO EW55 Magnetic 20000mAh แบตเตอรี่สำรอง PD 20W | QC 3.0 wireless power bank แม่เหล็ก QI Wireless Charge 15W แบตสำรอง",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1192329957%2F44473012282",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81zth-meqz4gclcu133e",
    "price": 579,
    "note": "ของช่วยให้ชีวิตทำงาน/เรียนออนไลน์ลื่นขึ้น",
    "category": "แก็ดเจ็ตน่าใช้",
    "tags": [
      "ทำงาน",
      "เครื่องมือ"
    ]
  },
  {
    "id": "shopee-25989999682",
    "title": "Taokinall รับประกัน1 ปี ชุดชาร์จเร็ว 33W 44W Super Fast Charge (สายชาร์จเร็ว+หัวชาร์จ) 6Aสายชาติเร็ว type c",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F1229481833%2F25989999682",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81ztk-ml39ebk4ye4j29",
    "price": 169,
    "note": "ของช่วยให้ชีวิตทำงาน/เรียนออนไลน์ลื่นขึ้น",
    "category": "แก็ดเจ็ตน่าใช้",
    "tags": [
      "ทำงาน",
      "เครื่องมือ"
    ]
  },
  {
    "id": "shopee-20105876438",
    "title": "อัพเกรดใหม่ล่าสุด!! Hoco C80T-DC96T Fast Charger หัวชาร์จเร็ว Type-C PD Quick Charge 20W หัวPD รองรับชาร์จเร็ว",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F374944741%2F20105876438",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-7ra0t-mdh342ze9cou7a",
    "price": 111,
    "note": "ของช่วยให้ชีวิตทำงาน/เรียนออนไลน์ลื่นขึ้น",
    "category": "แก็ดเจ็ตน่าใช้",
    "tags": [
      "ทำงาน",
      "เครื่องมือ"
    ]
  },
  {
    "id": "shopee-26003141831",
    "title": "【ส่งจากไทย มาใหม่ 1ชุด 5ชิ้น】เคสสายชาร์จ สำหรับ vivo 80w /90w  สายชาร์จ ลายการ์ตูนน่ารัก  Cable Bite",
    "url": "https://shope.ee/an_redir?origin_link=https%3A%2F%2Fshopee.co.th%2Fproduct%2F178623700%2F26003141831",
    "imageUrl": "https://cf.shopee.co.th/file/th-11134207-81ztm-mgyw369aglqn4e",
    "price": 16,
    "note": "ของช่วยให้ชีวิตทำงาน/เรียนออนไลน์ลื่นขึ้น",
    "category": "แก็ดเจ็ตน่าใช้",
    "tags": [
      "ทำงาน",
      "เครื่องมือ"
    ]
  }
];
