import { config } from "dotenv";

// โหลด env ก่อนอ่านค่า (รองรับ ENV_FILE override เหมือน db/migrate.ts)
const envFile = process.env.ENV_FILE;
if (envFile) config({ path: envFile });
config({ path: ".env.local" });
config({ path: ".env" });

import { createReadStream, writeFileSync } from "node:fs";
import { Readable } from "node:stream";
import { resolve } from "node:path";
import { parse } from "csv-parse";
import { SHOPEE_BUCKETS, type ShopeeBucket } from "./shopee-buckets";
import type { ShopeeProduct } from "../lib/shopee-products";

/**
 * คัดสินค้าขายดีจาก Shopee "Product Feed" (CSV) → เขียนทับ lib/shopee-products.generated.ts
 *
 * ที่มาของฟีด: affiliate.shopee.co.th → รูป → รายการ feed สินค้า → "ดูลิงก์" (ดาวน์โหลด CSV ลิงก์)
 * ฟีดอัพเดทเองทุกวัน + ลิงก์ในฟีด (product_short link) เป็น affiliate link ของบัญชีเรา
 *
 * ใช้:
 *   npm run shopee:fetch                 # ดึงจากฟีดจริง (ต้องมี SHOPEE_FEED_URL ใน .env.local) + เขียนไฟล์
 *   npm run shopee:fetch -- --dry        # ดูตารางผลลัพธ์ ไม่เขียนไฟล์
 *   npm run shopee:fetch -- --file a.csv # อ่านจากไฟล์ในเครื่อง (โหมดโหลดเอง / เทส)
 *   npm run shopee:fetch -- --max 50000  # จำกัดจำนวนแถวที่ scan (เทส/ฟีดใหญ่)
 *
 * ⚠️ ฟีดมี ~1,000,000 แถว/ไฟล์ → เรา "stream อ่านทีละแถว" ไม่โหลดทั้งก้อนเข้า memory
 */

// ───────── ค่าปรับได้ ─────────
const OUT_FILE = resolve(process.cwd(), "lib/shopee-products.generated.ts");
/** คุณภาพขั้นต่ำก่อนคัด (กันของเรตติ้งต่ำ/ของหมด) */
const MIN_RATING = 4.0;
const MIN_STOCK = 1;
/** ต้องมีคอลัมน์เหล่านี้ (subset ที่ใช้จริง) */
type FeedRow = Record<string, string>;

// ───────── args ─────────
function argValue(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
const DRY = process.argv.includes("--dry");
const FILE = argValue("--file");
const MAX_ROWS = Number(argValue("--max")) || Infinity;

// ───────── คะแนน: ขายดี × เรตติ้ง ─────────
// หมายเหตุ: ฟีด CSV "ไม่มี" คอลัมน์ commission → ใช้ยอดขาย×เรตติ้งแทน
// (log10 ยอดขาย กันตัว mega-seller กินรวบ)
function score(row: FeedRow): number {
  const sold = Number(row.item_sold) || 0;
  const rating = Number(row.item_rating) || 0;
  return Math.log10(sold + 1) * (rating / 5);
}

// ───────── จับสินค้าเข้าชั้น (ชั้นแรกที่ match ชนะ) ─────────
function matchBucket(title: string): ShopeeBucket | undefined {
  const t = (title || "").toLowerCase();
  if (!t) return undefined;
  return SHOPEE_BUCKETS.find((b) =>
    b.match.some((term) => t.includes(term.toLowerCase())),
  );
}

function toProduct(row: FeedRow, bucket: ShopeeBucket): ShopeeProduct {
  const priceRaw = Number(row.sale_price) || Number(row.price) || 0;
  const price = priceRaw > 0 ? Math.round(priceRaw) : undefined;
  const img = row.image_link || undefined;
  return {
    id: `shopee-${row.itemid}`,
    title: row.title,
    url: row["product_short link"], // ← affiliate link (an_redir) ไม่ใช่ product_link เปล่า
    ...(img ? { imageUrl: img } : {}),
    ...(price ? { price } : {}),
    note: bucket.note,
    category: bucket.category,
    tags: bucket.tags,
    ...(bucket.featured ? { featured: true } : {}),
  };
}

// ───────── serialize เป็นไฟล์ .ts (stable diff) ─────────
function renderFile(products: ShopeeProduct[]): string {
  const stamp = new Date().toISOString().slice(0, 10);
  return `/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-shopee-products.ts — ห้ามแก้ด้วยมือ
// รันใหม่ด้วย: npm run shopee:fetch  (ปรับหมวด/คำค้นที่ scripts/shopee-buckets.ts)
// อัปเดตล่าสุด: ${stamp} — ${products.length} สินค้า
import type { ShopeeProduct } from "./shopee-products";

export const GENERATED_PRODUCTS: ShopeeProduct[] = ${JSON.stringify(products, null, 2)};
`;
}

// ───────── แหล่งข้อมูล: ไฟล์ในเครื่อง หรือ stream จาก feed URL ─────────
async function openFeedStream(): Promise<NodeJS.ReadableStream> {
  if (FILE) {
    console.log(`[shopee] อ่านจากไฟล์: ${FILE}`);
    return createReadStream(FILE);
  }
  const url = process.env.SHOPEE_FEED_URL;
  if (!url) {
    throw new Error(
      "ไม่พบ SHOPEE_FEED_URL (และไม่ได้ส่ง --file)\n" +
        "→ ที่ affiliate.shopee.co.th → รูป → รายการ feed สินค้า → ดูลิงก์ → คัดลอก URL\n" +
        "  ใส่ใน .env.local:  SHOPEE_FEED_URL=https://affiliate.shopee.co.th/api/v1/datafeed/download?id=...",
    );
  }
  console.log("[shopee] ดึงฟีดจาก SHOPEE_FEED_URL (ตาม redirect อัตโนมัติ) …");
  const res = await fetch(url); // fetch ตาม 302 → signed mkt-proxy URL ให้เอง
  if (!res.ok || !res.body) {
    throw new Error(`ดึงฟีดไม่สำเร็จ: HTTP ${res.status}`);
  }
  return Readable.fromWeb(res.body as import("stream/web").ReadableStream);
}

// ───────── main ─────────
async function main() {
  const source = await openFeedStream();
  const parser = source.pipe(
    parse({
      columns: true,
      bom: true,
      relax_column_count: true,
      skip_records_with_error: true,
    }),
  );

  const perBucket = new Map<string, { row: FeedRow; s: number }[]>();
  for (const b of SHOPEE_BUCKETS) perBucket.set(b.category, []);
  const seen = new Set<string>();
  let scanned = 0;
  let matched = 0;

  for await (const row of parser as AsyncIterable<FeedRow>) {
    scanned++;
    if (scanned > MAX_ROWS) break;
    if (scanned % 100000 === 0)
      process.stdout.write(`\r[shopee] scan ${scanned} แถว, เจอ ${matched} …`);

    const bucket = matchBucket(row.title);
    if (!bucket) continue;
    if (!row["product_short link"]) continue;
    if ((Number(row.item_rating) || 0) < MIN_RATING) continue;
    if ((Number(row.stock) || 0) < MIN_STOCK) continue;
    const id = String(row.itemid);
    if (!id || seen.has(id)) continue;
    seen.add(id);
    perBucket.get(bucket.category)!.push({ row, s: score(row) });
    matched++;
  }
  console.log(`\n[shopee] scan เสร็จ ${scanned} แถว — เข้าเกณฑ์ ${matched} ตัว`);

  // คัด top-N ต่อชั้น (เรียงคะแนนมาก→น้อย) ตามลำดับ bucket
  const products: ShopeeProduct[] = [];
  const rows: Record<string, string | number>[] = [];
  for (const bucket of SHOPEE_BUCKETS) {
    const picked = perBucket
      .get(bucket.category)!
      .sort((a, b) => b.s - a.s)
      .slice(0, bucket.limit);
    for (const { row, s } of picked) {
      products.push(toProduct(row, bucket));
      rows.push({
        หมวด: bucket.category,
        สินค้า: (row.title || "").slice(0, 38),
        ยอดขาย: Number(row.item_sold) || 0,
        เรตติ้ง: Number(row.item_rating) || 0,
        ราคา: Number(row.sale_price) || Number(row.price) || 0,
        คะแนน: Math.round(s * 100) / 100,
      });
    }
  }

  if (products.length === 0) {
    throw new Error(
      "ไม่ได้สินค้าเลยสักตัว — ไม่เขียนไฟล์ (ของเดิมยังอยู่ครบ)\n" +
        "ลองเพิ่มคำใน scripts/shopee-buckets.ts (match) หรือเช็คว่าฟีดมีสินค้าหมวดนั้น",
    );
  }

  console.log(`\n[shopee] คัดได้ ${products.length} สินค้า:`);
  console.table(rows);

  if (DRY) {
    console.log("\n[shopee] --dry: ยังไม่เขียนไฟล์");
    return;
  }

  writeFileSync(OUT_FILE, renderFile(products), "utf8");
  console.log(`\n[shopee] เขียน ${OUT_FILE} ✅`);
  console.log("[shopee] ตรวจก่อน commit:  git diff lib/shopee-products.generated.ts");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("\n[shopee] ล้มเหลว:", err instanceof Error ? err.message : err);
    process.exit(1);
  });
